# Generated by Django 3.1 on 2020-08-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200830_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='course_information',
            field=models.CharField(default='This is the result of course', max_length=500),
            preserve_default=False,
        ),
    ]
